### ISSUE TITLE
FII_USE_METHOD_REFERENCE false positive

### ISSUE THREAD

**Issue by Serranya** [mebigfatguy/fb-contrib#388] opened 2020-02-20 16:22 UTC
The following code triggres an FII_USE_METHOD_REFERENCE warning

```java
int[] updateCount = ...
Arrays.stream(updateCount).mapToObj(i -> i == 1 ? Boolean.TRUE : Boolean.FALSE).allMatch(b -> b);
```

I have rewritten the code to the more concise
```java
int[] updateCount = ...
Arrays.stream(updateCount).allMatch(i -> i == 1);
```
which works. But the warning still seems like a false positive.

**Comment by ThrawnCA** [comment] 2020-02-21 02:53
I suspect it was complaining about the `i -> i` reference. It probably could have been replaced with something like `Boolean.TRUE::equals`

**Comment by Serranya** [comment] 2020-02-21 09:12
Ahh I see. If this is intentional im fine with closing the bug.

**Comment by mebigfatguy** [comment] 2020-02-23 19:01
Seems like the problem is the compiler is generating two lambda methods for this one mapToObject invocation. The first

  private static java.lang.Boolean lambda$20(int);
    descriptor: (I)Ljava/lang/Boolean;
    flags: ACC_PRIVATE, ACC_STATIC, ACC_SYNTHETIC
    Code:
      stack=2, locals=1, args_size=1
         0: iload_0
         1: iconst_1
         2: if_icmpne     11
         5: getstatic     #322                // Field java/lang/Boolean.TRUE:Ljava/lang/Boolean;
         8: goto          14
        11: getstatic     #328                // Field java/lang/Boolean.FALSE:Ljava/lang/Boolean;
        14: areturn

and the second

  private static boolean lambda$21(java.lang.Boolean);
    descriptor: (Ljava/lang/Boolean;)Z
    flags: ACC_PRIVATE, ACC_STATIC, ACC_SYNTHETIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokevirtual #335                // Method java/lang/Boolean.booleanValue:()Z
         4: ireturn

The second lambda is clearly the same as Boolean::valueOf and that is what is being reported. However you didn't write two lambdas the compiler did. Have it figure out how to address this.

**Comment by mebigfatguy** [comment] 2020-02-23 19:33
thanks for the report, should be fixed.

**Closed as completed** 2020-02-24 06:25 UTC
Labels: needs investigation
