### ISSUE TITLE
LSYC_LOCAL_SYNCHRONIZED_COLLECTION not detected on StringBuffer

### ISSUE THREAD

**Issue by DTecheira** [mebigfatguy/fb-contrib#47] opened 2015-06-10 18:02 UTC
I have found an inconsistent behaviour on LSYC_LOCAL_SYNCHRONIZED_COLLECTION, which is not always reproting for StringBuffer usages.

In the following code, there are 2 equally wrong uses of StringBuffer, yet only one is ever reported.

```
public class StringBufferTest {

	private static String TAG = "TAG";

	public void test() {
		// This one is not reported as LSYC_LOCAL_SYNCHRONIZED_COLLECTION
		final StringBuffer stringBuffer = new StringBuffer().append("agrego ").append("un ");
		stringBuffer.append("string ");
		Log.i(TAG, stringBuffer.toString());

		// This one gets reported as LSYC_LOCAL_SYNCHRONIZED_COLLECTION
		final StringBuffer stringBuffer2 = new StringBuffer();
		stringBuffer2.append("agrego ");
		stringBuffer2.append("un ");
		stringBuffer2.append("string ");
		Log.i(TAG, stringBuffer2.toString());
	}
}
```

I checked the dissasembled code, thinking maybe the compiler was changing the other `StringBuffer` (after all, I'm using it with constants), yet it's not.

> $ javap -c test/StringBufferTest.class
> Compiled from "StringBufferTest.java"
> public class test.StringBufferTest {
>   public test.StringBufferTest();
>     Code:
>        0: aload_0
>        1: invokespecial #1                  // Method java/lang/Object."<init>":()V
>        4: return
> 
>   public void test();
>     Code:
>        0: new           #2                  // class java/lang/StringBuffer
>        3: dup
>        4: invokespecial #3                  // Method java/lang/StringBuffer."<init>":()V
>        7: ldc           #4                  // String agrego
>        9: invokevirtual #5                  // Method java/lang/StringBuffer.append:(Ljava/lang/String;)Ljava/lang/StringBuffer;
>       12: ldc           #6                  // String un
>       14: invokevirtual #5                  // Method java/lang/StringBuffer.append:(Ljava/lang/String;)Ljava/lang/StringBuffer;
>       17: astore_1
>       18: aload_1
>       19: ldc           #7                  // String string
>       21: invokevirtual #5                  // Method java/lang/StringBuffer.append:(Ljava/lang/String;)Ljava/lang/StringBuffer;
>       24: pop
>       25: getstatic     #8                  // Field TAG:Ljava/lang/String;
>       28: aload_1
>       29: invokevirtual #9                  // Method java/lang/StringBuffer.toString:()Ljava/lang/String;
>       32: invokestatic  #10                 // Method android/util/Log.i:(Ljava/lang/String;Ljava/lang/String;)I
>       35: pop
>       36: new           #2                  // class java/lang/StringBuffer
>       39: dup
>       40: invokespecial #3                  // Method java/lang/StringBuffer."<init>":()V
>       43: astore_2
>       44: aload_2
>       45: ldc           #4                  // String agrego
>       47: invokevirtual #5                  // Method java/lang/StringBuffer.append:(Ljava/lang/String;)Ljava/lang/StringBuffer;
>       50: pop
>       51: aload_2
>       52: ldc           #6                  // String un
>       54: invokevirtual #5                  // Method java/lang/StringBuffer.append:(Ljava/lang/String;)Ljava/lang/StringBuffer;
>       57: pop
>       58: aload_2
>       59: ldc           #7                  // String string
>       61: invokevirtual #5                  // Method java/lang/StringBuffer.append:(Ljava/lang/String;)Ljava/lang/StringBuffer;
>       64: pop
>       65: getstatic     #8                  // Field TAG:Ljava/lang/String;
>       68: aload_2
>       69: invokevirtual #9                  // Method java/lang/StringBuffer.toString:()Ljava/lang/String;
>       72: invokestatic  #10                 // Method android/util/Log.i:(Ljava/lang/String;Ljava/lang/String;)I
>       75: pop
>       76: return
> 
>   static {};
>     Code:
>        0: ldc           #11                 // String TAG
>        2: putstatic     #8                  // Field TAG:Ljava/lang/String;
>        5: return
> }

**Comment by mebigfatguy** [comment] 2015-06-10 20:54
Thanks for the report. Yes this is definitely a false negative.

The problem is that the StringBuffer is never saved to a register (unlike the example that works), until after an append call is made.

this means, that at the time the append call is made, we haven't stored anywhere (except on the stack) that the item is a synchronized collection. then the append call is made, and findbugs (proper) creates a new stack entry for that result (throwing away the original entry for the stringbuffer (not knowing that the one returned by append is the same one). Thus by the time the store happens, i've lost track of that this came from a simply created local StringBuffer.

I'll poke around and see if there is something i can do here. It probably is a reasonably common pattern to miss. I probably have to tell the detector that append returns itself, and to do something special.

thanks again.

**Comment by mebigfatguy** [comment] 2015-06-10 21:16
i believe i've pushed a fix that should report your issue, now.

thanks for the report, reopen, or report new if there are still issues.

**Closed by mebigfatguy** 2015-06-10 21:16 UTC

**Comment by jsotuyod** [comment] 2015-06-10 21:36
When can we expect a 6.2.1 release with this and #46 fixed? Both were reported by [my company](https://github.com/Monits), and we would love to verify both fixes

**Comment by mebigfatguy** [comment] 2015-06-11 01:23
Version 6.2.1 has just been pushed to maven central, it will take a few hours for it to show up there.

**Comment by jsotuyod** [comment] 2015-06-11 01:59
Thanks for the amazing job! Will test it tomorrow first thing in the morning.

**Comment by jsotuyod** [comment] 2015-06-11 16:50
I can confirm both cases are no more. 

Amazing work as always.
