### ISSUE TITLE
AI_ANNOTATION_ISSUES_NEEDS_NULLABLE  and lambdas does not work well ?

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#260] opened 2018-01-25 14:56 UTC
I am getting: 

Method org.spf4j.base.Reflections.lambda$getConstructor$3(Constructor) that can return null, is missing a @Nullable annotation [org.spf4j.base.Reflections] At Reflections.java:[lines 293-294] AI_ANNOTATION_ISSUES_NEEDS_NULLABLE

at:

https://github.com/zolyfarkas/spf4j/blob/master/spf4j-core/src/main/java/org/spf4j/base/Reflections.java#L293

Any ideas?

**Comment by mebigfatguy** [comment] 2018-01-26 02:42
Thanks for the report.

this method
{
          cons.setAccessible(true);
          return null;
        }

can indeed return. The problem is you can't annotate it. so i'll fix that

**Comment by mebigfatguy** [comment] 2018-01-26 02:58
should be fixed, thanks!

**Closed as completed by mebigfatguy** 2018-01-26 02:58 UTC
