### ISSUE TITLE
False positive PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS on Java8 stream methods

### ISSUE THREAD

**Issue by afrin216** [mebigfatguy/fb-contrib#128] opened 2016-08-01 15:19 UTC
Hi. We keep getting `PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS` false positives with streams in Java 8. An example code snippet would be 

```
Arrays.asList("a", "b", "c").stream().collect(Collectors.toList());
Arrays.asList("x", "y", "z").stream().filter("x"::equalsIgnoreCase).collect(Collectors.toList());
```

I believe it's due to inability to distinguish between the adjacent `Collectors.toList()` calls where we can't assign the collector to a variable beforehand because the two streams might be having different class types or properties (parallel/sequential) where `Collectors.toList()` adapts itself based on the stream input.

Could you please look into this and maybe exclude these methods from type check? Thanks a lot for your awesome project!

**Comment by mebigfatguy** [comment] 2016-08-01 18:09
Thanks for the report, i believe this is a duplicate of #122 which was just fixed, in master. If you could give that a go, and see if it fixes it for you that'd be great. Open this up again if not.

**Closed by mebigfatguy** 2016-08-01 18:09 UTC

**Comment by danielfcastro** [comment] 2017-05-26 16:49
Same thing here

JSONObject xmlJSONObj = XML.toJSONObject(xmlCobol);
String value = xmlJSONObj.getJSONObject(TAG_NAME_PROGRAMA_COBOL).getJSONObject(LINHA).get(IDENTIDADE).toString())

**Comment by mebigfatguy** [comment] 2017-05-26 18:09
thanks for the report, but it is difficult for me to figure this one what the issue is here. Can you provide a compilable sample?

**Comment by danielfcastro** [comment] 2018-04-11 20:33
An example of false positive for this is the excerpt of class definitition below.


private Integer pageSize = Integer.MIN_VALUE;
private Long numberOfBrokers = Long.MIN_VALUE;
private Integer numberOfPages = Integer.MIN_VALUE;

**Comment by mebigfatguy** [comment] 2018-04-12 00:52
well in this case, it's reporting the double Integer.valueOf(Integer.MIN_VALUE) calls being executed twice. Now granted that's a pretty stupid report as it's trivial, and in a instance initializer.
