### ISSUE TITLE
fb-contrib:PSC_PRESIZE_COLLECTIONS false positive?

### ISSUE THREAD

**Issue by alixwar** [mebigfatguy/fb-contrib#269] opened 2018-03-22 13:22 UTC
Hi,
I have a case when I get a violation of rule `fb-contrib:PSC_PRESIZE_COLLECTIONS`. The size of strings is not known (could be calculated through conversions of course but that would require extra resources just to save some resources...).

Minimal sample to reproduce:
```
public void foo(final Iterable<String> strings) {
   final List<String> stringList = new ArrayList<>(); // Violation detected here
   for (final String string : strings) {
      stringList.add(string);
   }
}
```

FB-contrib version: 7.0.0

**Comment by ThrawnCA** [comment] 2018-03-23 00:27
Can you try with version 7.2.0? There were recent fixes for this: https://github.com/mebigfatguy/fb-contrib/issues/247

**Comment by mebigfatguy** [comment] 2018-03-23 02:47
Hi alixwar, thanks for the report. I've added your example as a test case, but it appears fb-contrib handles it correctly. Perhaps as ThrawnCA states, it has already been fixed. Or perhaps there is some other issue, (different compiler?) or such. I will close it, but if 7.2.1 doesn't address this, feel free to reopen.

**Comment by alixwar** [comment] 2018-03-23 07:59
Thanks for the feedback @mebigfatguy 
I'll post an update if I see this on the newer version

**Comment by alixwar** [comment] 2018-05-02 09:54
@mebigfatguy 
I re-analyzed my project with 7.2.1sb and it still shows as a violation.
Please reopen this.

**Comment by mebigfatguy** [comment] 2018-05-09 00:56
can you post the 
javap -v
output for this method?

**Comment by mebigfatguy** [comment] 2018-05-24 00:44
ok, actually i think i found an issue that is related and i'm guessing is the cause of this one too. so i'm going to close for now, and if 7.4.2 doesn't fix your issues, please reopen.

**Closed as completed by mebigfatguy** 2018-05-24 00:44 UTC
