### ISSUE TITLE
LSC_LITERAL_STRING_COMPARISON False Positive on String Switch

### ISSUE THREAD

**Issue by NicholasMoser** [mebigfatguy/fb-contrib#275] opened 2018-05-02 15:32 UTC
Hello, I'm encountering what I believe to be a false positive LSC_LITERAL_STRING_COMPARISON for a String based switch statement. Here is example code:

```
        public void propertyChange(final PropertyChangeEvent event)
        {
            Control control = viewer.getControl();

            if (control != null && !control.isDisposed() && event != null)
            {
                String property = event.getProperty();
                if (property != null)
                {
                    switch (property)
                    {
                    case Example.STRING1:
                    case Example.STRING2:
                    case Example.STRING3:
                    case Example.STRING4:
                        viewer.refresh();
                        break;
                    default:
                        String[] propChange = new String[] {
                                        property
                        };
                        viewer.update(event.getNewValue(), propChange);
                        break;
                    }
                }
            }
        }
```

It triggers as LSC_LITERAL_STRING_COMPARISON on the line with `switch (property)`, but shouldn't that be fixed by the null check two lines before? It is true that it is doing a literal String comparison, but isn't that only unsafe when the String could be null? I'm using fb-contrib 7.2.1.sb with SpotBugs in Eclipse. I'm compiling against Java 8. Maybe related? https://github.com/mebigfatguy/fb-contrib/pull/13

I assume I'm missing something obvious. Thanks 😄

**Comment by ThrawnCA** [comment] 2018-05-03 00:59
...I don't think that this detector is supposed to fire on `switch` statements at all. It may well be an oddity of the Eclipse compiler.

**Comment by NicholasMoser** [comment] 2018-05-03 14:46
I see. I'll do some personal investigation and see if I can figure it out myself. If I do I'll post an update here.

Thanks for the response.

**Comment by mebigfatguy** [comment] 2018-05-04 00:30
would you mind running

javap -v YourClass, and pasting the output for the 'propertyChange' method?

**Comment by NicholasMoser** [comment] 2018-05-08 15:13
https://gist.github.com/NicholasMoser/f3391dc1e3de9a2a3cc1e8eff7e0318b

I made minor modifications to the source code to remove references to our codebase (particularly the Strings it is switching on). I also made a minor modification to the output to remove references to the class name, instead replacing it with (this class). I made sure to rerun the site and am still seeing LSC_LITERAL_STRING_COMPARISON on the `switch (property)` line.

Thanks for looking into this! :)

**Comment by mebigfatguy** [comment] 2018-05-08 19:24
ah interesting, it's a tableswitch with strings, (rather than lookupswitch) i wouldn't have expected that. ok, will fix shortly.

**Comment by mebigfatguy** [comment] 2018-05-08 19:33
that is really strange, are you doing something tricky that is causing the hashCodes for A1, A2, A3, and A4 to be sequential numbers? (2064, 2065, 2066, 2067)?

Something seems wrong there...

oh, well, it should be fixed. If you'd like to try the HEAD of the branch spotbugs to see, that's be great as i can't reproduce the class file like you have it.

**Closed as completed** 2018-05-08 19:34 UTC

**Comment by NicholasMoser** [comment] 2018-05-09 14:10
>that is really strange, are you doing something tricky that is causing the hashCodes for A1, A2, A3, and A4 to be sequential numbers? (2064, 2065, 2066, 2067)?

Not that I'm aware of. I just picked A1, A2, and A3 as example Strings, I was noticing the issue occur with any kind of String that I tried to use.

>oh, well, it should be fixed. If you'd like to try the HEAD of the branch spotbugs to see, that's be great as i can't reproduce the class file like you have it.

Just tested against 7.2.2.sb-SNAPSHOT at branch spotbugs. Works like a charm. Thanks for the help! 👍
