### ISSUE TITLE
BED_BOGUS_EXCEPTION_DECLARATION does not track exceptions thrown by anonymous inner classes

### ISSUE THREAD

**Issue by Intropy** [mebigfatguy/fb-contrib#137] opened 2016-09-15 17:01 UTC
Example snippet:
```
public static TypedFoo<String> makeStringFoo(final InputStream inputStream) throws SAXException, JAXBException {
  return new TypedFoo<String>(inputStream, String.class) {
    @Override
    protected void bar() {}
  };
}
```

The checker says that the code declares that SAXException, JAXBException are thrown when they aren't. However, they are getting thrown. the TypedFoo constructor throws them. And the checker does not claim that the TypedFoo's constructor is wrong when it declares that it throws SAXException, JAXBException.

Full example (produced by mebigfatguy): http://pastebin.com/x4mkbbid

**Comment by mebigfatguy** [comment] 2016-09-15 18:02
This is a real issue. It is caused by an unexpected problem in the java byte code for the anonymous class, that being the anonymous constructor does not have an ExceptionTable defined for it, when it clearly should. I wonder if this is a bug with javac, or just something i don't understand.

**Comment by mebigfatguy** [comment] 2016-09-17 00:40
thanks! should be fixed on trunk

**Closed by mebigfatguy** 2016-09-17 00:40 UTC
